export const REGIONS = [
  'Full Body',
  'Head',
  'Neck',
  'Chest',
  'Upper Back',
  'Abdomen',
  'Lower Back',
  'Left Shoulder',
  'Right Shoulder',
  'Left Arm',
  'Right Arm',
  'Left Hand',
  'Right Hand',
  'Left Hip',
  'Right Hip',
  'Left Thigh',
  'Right Thigh',
  'Left Lower Leg',
  'Right Lower Leg',
  'Left Foot',
  'Right Foot',
]
